services:
  localstack:
    image: localstack/localstack:4.9.2
    ports:
      - "4567:4566" # LocalStack Gateway (avoiding conflict with ai-defra-search-data on 4566)
      - "4570-4619:4510-4559" # external services port range
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: ${DEBUG:-0}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: sqs
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack-agent:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data

  ai-defra-search-agent:
    build:
      context: .
      target: development
    ports:
      - 8086:8086
      - 5679:5679
    links:
      - "mongodb:mongodb"
      - "localstack:localstack"
    depends_on:
      mongodb:
        condition: service_started
      localstack:
        condition: service_healthy
    profiles:
      - service
    env_file:
      - ".env"
    environment:
      PORT: ${PORT:-8086}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}

    volumes:
      - ./app:/home/nonroot/app
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml
          target: /home/nonroot/pyproject.toml
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    external: true
    name: ai-defra-search-data_cdp-tenant
