services:
  localstack:
    image: localstack/localstack:4
    ports:
      - "5566:4566" # LocalStack Gateway
      - "5510-5559:4510-4559" # external services port range
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant
    profiles:
      - service

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data

  ai-defra-search-agent:
    build:
      context: .
      target: development
    ports:
      - 8086:8086
      - 5679:5679
    links:
      - "mongodb:mongodb"
    depends_on:
      mongodb:
        condition: service_started
    profiles:
      - service
    env_file:
      - ".env"
    environment:
      PORT: ${PORT:-8086}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}
      LOCALSTACK_URL: ${LOCALSTACK_URL:-http://localstack:4566}
    volumes:
      - ./app:/home/nonroot/app
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml
          target: /home/nonroot/pyproject.toml
    networks:
      - cdp-tenant

  chat-worker:
    build:
      context: .
      target: development
    entrypoint: []
    command: ["/home/nonroot/.venv/bin/python", "-m", "app.chat.worker"]
    env_file:
      - ".env"
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      LOCALSTACK_URL: ${LOCALSTACK_URL:-http://localstack:4566}
    depends_on:
      - mongodb
      - localstack
    networks:
      - cdp-tenant
    profiles:
      - service
volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
